-- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) >= 9 
    AND EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) < 20
GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
ORDER BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) ASC;