-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B, AUTHOR A
WHERE CATEGORY = '경제'
    AND B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;

