-- 코드를 입력하세요
SELECT FLOOR(PRICE/10000)*10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY FLOOR(PRICE/10000)*10000
ORDER BY PRICE_GROUP ASC;

-- 다른 풀이: 서브쿼리 사용 
-- SELECT PRICE_GROUP, COUNT(*) AS PRODUCTS
-- FROM (SELECT FLOOR(PRICE/10000)*10000 AS PRICE_GROUP
--       FROM PRODUCT)
-- GROUP BY PRICE_GROUP
-- ORDER BY PRICE_GROUP ASC; 
